In [3]:
import numpy as np

# Set the dimensions of the matrix
rows = 5
cols = 784

# Generate the matrix with signed integers in the range of -128 to 127 (int8 type)
matrix = np.random.randint(-128, 128, size=(rows, cols), dtype=np.int8)

# Function to convert signed integers to 8-digit hexadecimal format
def signed_to_hex(num):
    # Convert signed integers to a two's complement 8-digit hex representation
    # If the number is negative, we add 256 to convert to unsigned format
    if num < 0:
        return f'{num + 256:08X}'
    else:
        return f'{num:08X}'

# Create the MIF file and write the matrix
mif_filename = 'signed_matrix.mif'

with open(mif_filename, 'w') as mif_file:
    # Write the matrix directly as 8-digit hex numbers, one per line
    for row in matrix:
        for num in row:
            mif_file.write(signed_to_hex(num) + '\n')

print(f'MIF file with signed integers written to {mif_filename}')


MIF file with signed integers written to signed_matrix.mif


In [12]:
matrix

array([[ 122,  -93,   62, ...,  -71,   49,   96],
       [ 106,   72,  -18, ...,  -46,   61,   -1],
       [  62,  -99, -119, ...,   34,  -22,  -41],
       [  53,   46,  126, ...,   67, -100, -103],
       [ -87,  -10,   56, ..., -127,  -51,   57]], dtype=int8)

In [13]:
reshaped_matrix

array([[ 122,  -93,   62,   76,   78],
       [ -67,  113,  106,  122,   32],
       [ 110,   14,  -69,  -98,  -27],
       ...,
       [  28,  -37,   81,   74,   98],
       [ 123,  117,  -27,   69,    0],
       [  15,   61, -127,  -51,   57]], dtype=int8)

In [11]:
# Flatten the 5x784 matrix into a 1D array
flattened_matrix = matrix.flatten()

# Reshape the flattened array into a 784x5 matrix
reshaped_matrix = flattened_matrix.reshape((784, 5))

In [16]:
# Compute the product of the matrix and its transpose
result_matrix = np.dot(matrix, reshaped_matrix)

# Print the result matrix
result_matrix

array([[  21,    5,   18,  -43, -123],
       [  -2, -116,  114,  -51,   24],
       [ -75,  -13,  104,  107,  -22],
       [ -52,   37,  125,  -96,  -66],
       [  89,   66,  115,  -81,  -40]], dtype=int8)