In [63]:
import numpy as np

# Set the dimensions of the matrix
rows = 5
cols = 784

# Generate the matrix with signed integers in the range of -128 to 127 (int8 type)
matrix = np.random.randint(-128, 128, size=(rows, cols), dtype=np.int8)

# Function to convert signed integers to 32-bit two's complement hex
def signed_to_hex(num):
    # Convert to 32-bit signed int
    num_32bit = np.int32(num)
    # Convert to unsigned 32-bit for hex representation
    # & 0xFFFFFFFF ensures we get the full 32-bit representation
    unsigned_32bit = num_32bit & 0xFFFFFFFF
    return f'{unsigned_32bit:08X}'

# Create the MIF file and write the matrix
mif_filename = 'signed_matrix.mif'
with open(mif_filename, 'w') as mif_file:
    for row in matrix:
        for num in row:
            mif_file.write(signed_to_hex(num) + '\n')

print(f'MIF file with signed integers written to {mif_filename}')

MIF file with signed integers written to signed_matrix.mif


In [64]:
matrix.shape

(5, 784)

In [73]:
matrix

array([[  60,  103,  -25, ...,  117,  117,   78],
       [  72,  -74,  -43, ..., -111,   13, -115],
       [-122,  107,  -67, ...,   33,  -75,   71],
       [  55,  -61,   70, ...,   48,   20,   65],
       [  68,  109,  -55, ..., -116,   21,  109]], dtype=int8)

In [74]:
# Flatten the 5x784 matrix into a 1D array
flattened_matrix = matrix.flatten()

# Reshape the flattened array into a 784x5 matrix
reshaped_matrix = flattened_matrix.reshape((784, 5))

result_matrix = np.dot(matrix, reshaped_matrix)

# Print the result matrix
result_matrix

array([[ -12,  -71, -126,  -60,   81],
       [-104,  -98,  -10,   94,   66],
       [  34,   15,  -58,  -43,  -84],
       [  16,   75,    4,  -59,  -31],
       [  50, -107,  -23,   95,    7]], dtype=int8)

In [72]:
reshaped_matrix1 = flattened_matrix.reshape((5, 784))

In [69]:
reshaped_matrix1

array([[   2,   72,  112, ...,   65,   65,    7],
       [ 105, -121, -127, ...,   81,    2, -119],
       [  37,  126,  -97, ...,  100,  107,   55],
       [ -27,    8, -123, ...,  111,  -14,  -31],
       [  18,   -9,   59, ...,  127,   94, -100]], dtype=int8)

In [59]:
reshaped_matrix2.shape

(784, 5)

In [61]:
result_matrix = np.dot(reshaped_matrix1, reshaped_matrix2)

# Print the result matrix
result_matrix

array([[  -3,  -66,  -87,  -97,    6],
       [  82, -128, -103,  -67, -100],
       [ -42,    4,  -47,   83,   27],
       [ -73,   -9,   43,   61,  -82],
       [ -96, -112,  -31, -119, -116]], dtype=int8)