In [36]:
import numpy as np

# Set the dimensions of the matrix
rows = 5
cols = 784

# Generate the matrix with signed integers in the range of -128 to 127 (int8 type)
matrix = np.random.randint(-128, 128, size=(rows, cols), dtype=np.int8)

# Function to convert signed integers to 32-bit two's complement hex
def signed_to_hex(num):
    # Convert to 32-bit signed int
    num_32bit = np.int32(num)
    # Convert to unsigned 32-bit for hex representation
    # & 0xFFFFFFFF ensures we get the full 32-bit representation
    unsigned_32bit = num_32bit & 0xFFFFFFFF
    return f'{unsigned_32bit:08X}'

# Create the MIF file and write the matrix
mif_filename = 'signed_matrix.mif'
with open(mif_filename, 'w') as mif_file:
    for row in matrix:
        for num in row:
            mif_file.write(signed_to_hex(num) + '\n')

print(f'MIF file with signed integers written to {mif_filename}')

MIF file with signed integers written to signed_matrix.mif


In [52]:
matrix.shape

(5, 784)

In [53]:
matrix

array([[   2,   72,  112, ...,   65,   65,    7],
       [ 105, -121, -127, ...,   81,    2, -119],
       [  37,  126,  -97, ...,  100,  107,   55],
       [ -27,    8, -123, ...,  111,  -14,  -31],
       [  18,   -9,   59, ...,  127,   94, -100]], dtype=int8)

In [41]:
# Flatten the 5x784 matrix into a 1D array
flattened_matrix = matrix.flatten()

# Reshape the flattened array into a 784x5 matrix
reshaped_matrix2 = flattened_matrix.reshape((784, 5))

In [56]:
reshaped_matrix1 = flattened_matrix.reshape((5, 784))

In [57]:
reshaped_matrix[0]

array([ 122,  -93,   62,   76,   78,  -67,  113,  106,  122,   32,  110,
         14,  -69,  -98,  -27,  -61, -101, -128,  -38,  -71,  -83,   31,
         14,   68,  106,  -80,  -24,  -83, -103,  -36,  -34,   31,   25,
        117,   56,  127,  -47,   -8,   95,  -40, -117,  -43,   -3,  -14,
        -41,  -40, -121,  -28,  -33,  -57,  113,   -7,   36, -105,  113,
        -58,  -12, -122, -128,   79,   17,   67,   57,   50, -101,   -2,
         -7,  120,   43,   81,   68,  -92,  -65,  111,  -92,    6,  -38,
         56, -102,  -95,   59,  100,   -9,  -74,   46,  -58, -107,  117,
         88,   -8,    6, -127,   92,  102,   13,  -61,  119,  -72,  108,
         50,   44,   94,   44,  -13, -108,    9, -104,  -57, -102,  -25,
         10, -107,  -25,   47,   74,  -56, -109,  -78, -115,   74,  108,
         46,    0,  -66, -127,   41,  -72,  120,   10,  -61,  -56,   32,
       -118,   42,   76,  -98,   84,   59,    3,  117,   80,   49,  -97,
         60,  -50,   59,  -90,    2,   24,   44,  -

In [54]:
reshaped_matrix2[:,4]

array([ 107,   69,  -14, -103, -102,   48,   40,   16,   35, -113,   77,
        125,  -58,  -44,  -26, -112,  -53, -126,  -70,  -97,  -47, -115,
         50,   77,   28,   98,   71,   28,  -50,   -9,  -85,  123,  125,
         74,  -60,   79, -120,  -57,  -51,   33,   -8,  -29,   51,   44,
        119,  -12,   -3,  -41,   39,  126,   49,  -98,  125,  -70,  -31,
        -60,  -54,  122,  -32,  -25,  -59,  121,  -83,  -26,  -15,  -69,
        -76,  -50,   -1, -120,   96,   87,  -99,   91,   11,  123,    7,
         -6, -101,  -64,   64,   24,   59,  -62,   84, -125,   83,   29,
       -104,   40,   11,  -11,   36,  122,  127,   82, -100,  -36,  -18,
         25,  -55,   16,  -99, -126,   88,  -32,   47,   59,  -87,  -88,
          5,  -13,   66,    7,  -32,   55,  -80,   42,  -41,  -52,   16,
        -72,   -9,  123,   -6, -112,   56,  -66,  -59,  109,   -2,  -31,
        -25,  -81, -104,  -49,   81,  -75, -104,   -1,  100,   95,  -27,
         45,   38,  103,   53,   39,   23,   66,  -

array([[  -3,  -66,  -87,  -97,    6],
       [  82, -128, -103,  -67, -100],
       [ -42,    4,  -47,   83,   27],
       [ -73,   -9,   43,   61,  -82],
       [ -96, -112,  -31, -119, -116]], dtype=int8)