In [3]:
import numpy as np

# Set the dimensions of the matrix
rows = 5
cols = 784

# Generate the matrix with signed integers in the range of -128 to 127 (int8 type)
matrix = np.random.randint(-128, 128, size=(rows, cols), dtype=np.int8)

# Function to convert signed integers to 8-digit hexadecimal format
def signed_to_hex(num):
    # Convert signed integers to a two's complement 8-digit hex representation
    # If the number is negative, we add 256 to convert to unsigned format
    if num < 0:
        return f'{num + 256:08X}'
    else:
        return f'{num:08X}'

# Create the MIF file and write the matrix
mif_filename = 'signed_matrix.mif'

with open(mif_filename, 'w') as mif_file:
    # Write the matrix directly as 8-digit hex numbers, one per line
    for row in matrix:
        for num in row:
            mif_file.write(signed_to_hex(num) + '\n')

print(f'MIF file with signed integers written to {mif_filename}')


MIF file with signed integers written to signed_matrix.mif


In [12]:
matrix.

array([[ 122,  -93,   62, ...,  -71,   49,   96],
       [ 106,   72,  -18, ...,  -46,   61,   -1],
       [  62,  -99, -119, ...,   34,  -22,  -41],
       [  53,   46,  126, ...,   67, -100, -103],
       [ -87,  -10,   56, ..., -127,  -51,   57]], dtype=int8)

In [13]:
reshaped_matrix

array([[ 122,  -93,   62,   76,   78],
       [ -67,  113,  106,  122,   32],
       [ 110,   14,  -69,  -98,  -27],
       ...,
       [  28,  -37,   81,   74,   98],
       [ 123,  117,  -27,   69,    0],
       [  15,   61, -127,  -51,   57]], dtype=int8)

In [27]:
# Flatten the 5x784 matrix into a 1D array
flattened_matrix = matrix.flatten()

# Reshape the flattened array into a 784x5 matrix
reshaped_matrix2 = flattened_matrix.reshape((784, 5))

In [28]:
reshaped_matrix1 = flattened_matrix.reshape((5, 784))

In [29]:
reshaped_matrix1[0]

array([ 122,  -93,   62,   76,   78,  -67,  113,  106,  122,   32,  110,
         14,  -69,  -98,  -27,  -61, -101, -128,  -38,  -71,  -83,   31,
         14,   68,  106,  -80,  -24,  -83, -103,  -36,  -34,   31,   25,
        117,   56,  127,  -47,   -8,   95,  -40, -117,  -43,   -3,  -14,
        -41,  -40, -121,  -28,  -33,  -57,  113,   -7,   36, -105,  113,
        -58,  -12, -122, -128,   79,   17,   67,   57,   50, -101,   -2,
         -7,  120,   43,   81,   68,  -92,  -65,  111,  -92,    6,  -38,
         56, -102,  -95,   59,  100,   -9,  -74,   46,  -58, -107,  117,
         88,   -8,    6, -127,   92,  102,   13,  -61,  119,  -72,  108,
         50,   44,   94,   44,  -13, -108,    9, -104,  -57, -102,  -25,
         10, -107,  -25,   47,   74,  -56, -109,  -78, -115,   74,  108,
         46,    0,  -66, -127,   41,  -72,  120,   10,  -61,  -56,   32,
       -118,   42,   76,  -98,   84,   59,    3,  117,   80,   49,  -97,
         60,  -50,   59,  -90,    2,   24,   44,  -

In [33]:
reshaped_matrix2[:,4]

array([  78,   32,  -27,  -71,  106,  -36,   56,  -40,  -41,  -57,  113,
         79, -101,   81,  -92,  -95,   46,   -8,   13,   50, -108,  -25,
         74,   74, -127,  -61,   76,  117,  -50,   44,  -41,  -73,  119,
         70,   50,  -44,  -32,   65,   18,   35,  -95,   17,   77,    8,
        108,   27, -118,   98,   -4,   50, -100,  -92,  -87, -100,   61,
         10,   -1,   27,  -16,   23,   -1, -103,   47,  -48, -120, -105,
         90, -109,  125,   94,  116,  -76,   42,    6,   94,  -18,   75,
        126,   91,  -50,  -47, -127,  -79,  -54,  -91,  -78,   65,  107,
        -81,   16,  121,  -56,  -76,   57,   98,    8,  119,   94,  -54,
       -110, -118,   35,   34,  -79,   48,  -28,   98,   -1,   99,  -55,
       -119,  -99, -128,   78,  120,  125,   82,  -51, -113,  -24,  121,
         47,  103,   88,   88,   91,   -2, -127,  -86, -109,   18,   10,
         29,  -79, -110,  121,   64,  -92,  -21,  -15,   19,  121,  115,
        -32, -107,   83,   -9, -117, -107,  -74,   

In [35]:
# Compute the product of the matrix and its transpose
result_matrix = np.dot(reshaped_matrix1, reshaped_matrix2)

# Print the result matrix
result_matrix

array([[  21,    5,   18,  -43, -123],
       [  -2, -116,  114,  -51,   24],
       [ -75,  -13,  104,  107,  -22],
       [ -52,   37,  125,  -96,  -66],
       [  89,   66,  115,  -81,  -40]], dtype=int8)